backend/models/ExclusivePrice.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "ExclusivePrice".
 *
 * @property integer $ExclusivePriceID
 * @property string $StatusPrice
 * @property string $ImagePrice
 * @property string $VideoPrice
 */
class ExclusivePrice extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'exclusiveprice';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['StatusPrice','ImagePrice','VideoPrice','StatusSKUID','ImageSKUID','VideoSKUID'], 'required','on' => 'update'],
            [['StatusPrice','ImagePrice','VideoPrice','StatusSKUID','ImageSKUID','VideoSKUID'], 'required','on' => 'create'],
            [['StatusPrice'], 'number', 'numberPattern' => '/^\s*[-+]?[0-9]*[.,]?[0-9]+([eE][-+]?[0-9]+)?\s*$/'],        
            [['ImagePrice'], 'number', 'numberPattern' => '/^\s*[-+]?[0-9]*[.,]?[0-9]+([eE][-+]?[0-9]+)?\s*$/'],        
            [['VideoPrice'], 'number', 'numberPattern' => '/^\s*[-+]?[0-9]*[.,]?[0-9]+([eE][-+]?[0-9]+)?\s*$/'],        
            [['StatusPrice','ImagePrice','VideoPrice'],'number', 'min'=>0.01],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ExclusivePriceID' => 'Exclusive Price ID',
            'StatusPrice' => 'Status Price',
            'StatusSKUID' => 'Status Product ID',
            'ImagePrice' => 'Image Price',
            'ImageSKUID' => 'Image Product ID',
            'VideoPrice' => 'Video Price',
            'VideoSKUID' => 'Video Product ID',
        ];
    }
}

backend/controllers/ExclusivepriceController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\ExclusivePrice;
use backend\models\ExclusivePriceSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\filters\AccessControl;

/**
 * ExclusivePriceController implements the CRUD actions for ExclusivePrice model.
 */
class ExclusivepriceController extends Controller
{
    /*public function behaviors()
    {
        $session = Yii::$app->session;
        if(Yii::$app->user->identity->UserType == 1) {
            return [
                'access' => [
                    'class' => AccessControl::className(),
                    'rules' => [
                        [
                            'allow' => true,
                            'actions' => ['update'],
                            'roles' => ['@'],
                        ],
                    ],
                ],
            ];
        } else if(Yii::$app->user->identity->UserType == 2) {
            return [
                'access' => [
                    'class' => AccessControl::className(),
                    'rules' => [
                        [
                            'allow' => true,
                            'actions' => [''],
                            'roles' => ['@'],
                        ],
                    ],
                ],
            ];
        }
    }*/
    public function behaviors()
    {
        if(Yii::$app->user->identity->UserType == 3) {
            return \Yii::$app->getResponse()->redirect(array('/site/logout',302));
        }
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }
    public function beforeAction($action)
    {        
        if (\Yii::$app->getUser()->isGuest &&
            \Yii::$app->getRequest()->url !== Url::to(\Yii::$app->getUser()->loginUrl)
        ) {
            \Yii::$app->getResponse()->redirect(\Yii::$app->getUser()->loginUrl);
        }
        return parent::beforeAction($action);
    }
    
    /*public function cutNum( $number, $separator = '.', $format = 2 ){
        $response = '';
        $brokenNumber = explode( $separator, $number );
        $response = $brokenNumber[0] . $separator;
        if(isset($brokenNumber[1]) && $brokenNumber[1] !='') { 
            $brokenBackNumber = str_split($brokenNumber[1]);
            echo '<pre>';
            print_r($brokenBackNumber);
            die;
            if( $format < count($brokenBackNumber) ){
                for( $i = 1; $i <= $format; $i++ )
                    $response .= $brokenBackNumber[$i];
            }
            return $response;
        } else {
            return $number;
        }
    }*/


    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if(Yii::$app->user->identity->UserType == 1)
        {
            $model->ArtistID = $id;
        }
        if(isset($model->ExclusivePriceID))
        {
            $model->scenario = 'update';
        }
        else
        {
            $model->scenario = 'create';
        }
        
        if ($model->load(Yii::$app->request->post())) 
        {
            if($model->validate()) 
            {
                /*$model->StatusPrice  = $this->cutNum($_POST['ExclusivePrice']['StatusPrice'],'.',2);
                $model->ImagePrice  = $this->cutNum($_POST['ExclusivePrice']['ImagePrice'],'.',2);
                $model->VideoPrice  = $this->cutNum($_POST['ExclusivePrice']['VideoPrice'],'.',2);*/
                
                $model->StatusPrice  = $_POST['ExclusivePrice']['StatusPrice'];
                $model->ImagePrice  = $_POST['ExclusivePrice']['ImagePrice'];
                $model->VideoPrice  = $_POST['ExclusivePrice']['VideoPrice'];
                if(Yii::$app->user->identity->UserType == 1) {
                    $model->ArtistID = $_POST['ExclusivePrice']['ArtistID'];
                } else {
                    $model->ArtistID  = $id;
                }
                
                $model->save(false);
                Yii::$app->session->setFlash('success', 'Exclusive Price has been updated successfully');
                return $this->redirect(['update', 'id' => $model->ArtistID]);
            }    
            else 
            {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        } 
        else 
        {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    protected function findModel($id)
    {
        if (($model = ExclusivePrice::findOne(["ArtistID"=>$id])) !== null) {
            return $model;
        } else {
            return $model = new ExclusivePrice();
            //throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/exclusiveprice/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model backend\models\ExclusivePrice */
/* @var $form yii\widgets\ActiveForm */
$readOnlyForArtist = array('maxlength' => 100,'prompt'=>'--Select Artist--');
?>

<div class="exclusive-price-form">
    <?php $form = ActiveForm::begin(); ?>
    <?php
    if(Yii::$app->user->identity->UserType == 1)
    {
        echo $form->field($model, 'ArtistID')->dropDownList(\backend\models\Sticker::getArtistList(),$readOnlyForArtist);
    }
    ?>
    <?= $form->field($model, 'StatusPrice')->textInput(['maxlength' => 10]) ?>
    <?= $form->field($model, 'StatusSKUID')->textInput(['maxlength' => 100]) ?>
    <?= $form->field($model, 'ImagePrice')->textInput(['maxlength' => 10]) ?>
    <?= $form->field($model, 'ImageSKUID')->textInput(['maxlength' => 100]) ?>
    <?= $form->field($model, 'VideoPrice')->textInput(['maxlength' => 10]) ?>
    <?= $form->field($model, 'VideoSKUID')->textInput(['maxlength' => 100]) ?>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Save', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>
<?php 
$this->registerJs('
    $(document).ready(function() {
        $("#exclusiveprice-artistid").change(function() {
            var artistID = $("#exclusiveprice-artistid").val();
            document.location.href= "'.Url::to(['exclusiveprice/update']).'?id="+artistID;
        });
    });    
');
?>

backend/views/exclusiveprice/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\ExclusivePriceSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="exclusive-price-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'ExclusivePriceID') ?>

    <?= $form->field($model, 'StatusPrice') ?>

    <?= $form->field($model, 'ImagePrice') ?>

    <?= $form->field($model, 'VideoPrice') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/exclusiveprice/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\ExclusivePrice */

$this->title = 'Create Exclusive Price';
$this->params['breadcrumbs'][] = ['label' => 'Exclusive Prices', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="exclusive-price-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/exclusiveprice/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\ExclusivePriceSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Exclusive Prices';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="exclusive-price-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Exclusive Price', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'ExclusivePriceID',
            'StatusPrice',
            'ImagePrice',
            'VideoPrice',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

backend/views/exclusiveprice/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\ExclusivePrice */

$this->title = 'Update Exclusive Pricing';
$this->params['breadcrumbs'][] = ['label' => 'Exclusive Prices', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->ExclusivePriceID, 'url' => ['view', 'id' => $model->ExclusivePriceID]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="exclusive-price-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/exclusiveprice/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\ExclusivePrice */

$this->title = $model->ExclusivePriceID;
$this->params['breadcrumbs'][] = ['label' => 'Exclusive Prices', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="exclusive-price-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->ExclusivePriceID], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->ExclusivePriceID], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'ExclusivePriceID',
            'StatusPrice',
            'ImagePrice',
            'VideoPrice',
        ],
    ]) ?>

</div>